Name:           perl-MasonX-Request-WithApacheSession
Version:        0.31
Release:        1%{?dist}
Summary:        Add a session to the Mason Request object
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/MasonX-Request-WithApacheSession/
Source0:        http://www.cpan.org/modules/by-module/MasonX/MasonX-Request-WithApacheSession-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Apache::Session::Wrapper) >= 0.13
BuildRequires:  perl(HTML::Mason) >= 1.16
BuildRequires:  perl(Module::Build)
# Added for RHEL 6
BuildRequires:  perl(Time::HiRes)
Requires:       perl(Apache::Session::Wrapper) >= 0.13
Requires:       perl(HTML::Mason) >= 1.16
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module integrates Apache::Session into Mason by adding methods to the
Mason Request object available in all Mason components.

%prep
%setup -q -n MasonX-Request-WithApacheSession-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Sep 27 2012 "Nico Kadel-Garcia <nico.kadel@tufts.edu>" 0.31-0.2
- Add BuildRequires: Time::HiRes for RHEL 6

* Thu Sep 20 2012 "Nico Kadel-Garcia <nico.kadel@tufts.edu>" 0.31-0.1
- Specfile autogenerated by cpanspec 1.78.
